name := "cosmic-desktop"
packages := "cosmic-desktop"
dnf_weak_deps := "true"
base_images := "
quay.io/fedora-ostree-desktops/silverblue:41
quay.io/fedora-ostree-desktops/kinoite:41
"

import '../sysext.just'

all: default
